### ISSUE TITLE
Documentation for building tizen flutter plugins

### ISSUE THREAD

**Issue by Brendan-H** [flutter-tizen/plugins#109]
There are a couple of plugins I'd like to add (mainly a tizen version of googleapis), but I have no idea what is different on Tizen. I noticed there are a lot of contributors, so can somebody create basic documentation that highlights everything different?

**Comment by swift-kim** [comment]
Thank you for showing your interest in developing Flutter plugins for Tizen. Documenting how to create Tizen plugins is actually one of my TODO items (https://github.com/flutter-tizen/flutter-tizen/issues/60) but I didn't have much time to write it in detail. (Could anybody help me?)

Writing Tizen plugins shouldn't be much different from writing Android or iOS plugins because Tizen plugins work exactly in the same way as plugins on other platforms (over message channels) as illustrated in https://flutter.dev/docs/development/platform-integration/platform-channels. You just have to make sure you declared `tizen` under `platforms` in your plugin's pubspec file, e.g. as shown in https://github.com/flutter-tizen/plugins/blob/master/packages/package_info/pubspec.yaml so that the flutter-tizen tool can know that the package has Tizen native implementation. You can initialize a new plugin project by typing:

```sh
flutter-tizen create --template plugin my_plugin_name
```

and then some boilerplate code will be generated in the `my_plugin_name` directory. You will find the implementation file (`.cc`) in the project's `tizen/src` directory where you can use

- C++17 standards
- Tizen C APIs ([Tizen API references](https://docs.tizen.org/application/native/api/wearable/5.5/index.html))
- cpp_client_wrapper APIs ([header files in the engine repo](https://github.com/flutter-tizen/engine/tree/flutter-2.0.1-tizen/shell/platform/common/cpp/client_wrapper/include/flutter))

to implement platform channel APIs declared in Dart code.

You may notice that some of our plugins (such as url_launcher_tizen and shared_preferences_tizen) are based on Dart FFI but not C/C++ (some Windows plugins are also based on FFI). You don't have to care about them if you don't have understanding of FFI or the federated plugins architecture. All other plugins are written in C/C++.

> mainly a tizen version of googleapis

As far as I can see in the [googleapis package description](https://pub.dev/packages/googleapis), it doesn't look like a _plugin_ but a pure Dart package. Maybe you can use it on Tizen without porting as long as your device has a network connection.

FYI) On the contrary, [FlutterFire](https://firebase.flutter.dev/) packages are actually _plugins_ so you need to port them for use on Tizen devices (which is not actually possible because there's no Tizen native implementation of Firebase libraries).

> I noticed there are a lot of contributors,

They are all Samsung employees although not all of them are working for the same project. They are all familiar with Tizen development so they didn't have much difficulty with understanding how the things work. 😉

**Comment by Brendan-H** [comment]
That makes a lot of sense :) Thanks for giving an in-depth answer, it will help out a lot!
