### ISSUE TITLE
Writing unittests and mocks for native plugins using googletest

### ISSUE THREAD

**Issue by HakkyuKim** [flutter-tizen/plugins#386]
I've created a simple working example [here](https://github.com/HakkyuKim/plugins/commit/209b1331ac65e42511cb3a0db62b20d60211b7ae).

Steps to run the unittest:
1. Set the current working directory to `audioplayers/tizen`.
2. Run `cmake -B build && cmake --build build`
3. Run `./build/audioplayers_unittest`

```sh
Running main() from /home/hakkyu/mydir/project/flutter/plugins/packages/audioplayers/tizen/build/_deps/googletest-src/googletest/src/gtest_main.cc
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from AudioPlayerError
[ RUN      ] AudioPlayerError.BasicConstructor
[       OK ] AudioPlayerError.BasicConstructor (0 ms)
[----------] 1 test from AudioPlayerError (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 1 test.
```

Plugin developers need to configure `CMakeLists.txt` themselves to omit adding source files that include tizen headers. I don't think this can be avoided.

**Comment by swift-kim** [comment]
Do you run the test in the host environment? Tizen rootstraps do not include x64 libs but are shipped with only arm and x86 libs. This means that you can't use any Tizen API in the test. What kind of test cases are you going to add to the audioplayers_tizen package?

**Comment by HakkyuKim** [comment]
I was thinking of providing a way to add native tests if one needs it and not specifically for `audioplayers_tizen`, though it may benefit from it.

The current setting runs in a host environment so only wrapper classes with mocked Tizen APIs can be tested. I've tried configuring CMake to use Tizen compiler toolchains so that unittests(or integration tests since it's running on a Tizen platform) with Tizen APIs can be built and run on devices/emulators, but haven't succeeded yet.

The issue is open for discussion; whether the native testing feature is worth adding complexity, and so on.

**Comment by swift-kim** [comment]
Actually adding a native unit test to a Flutter plugin is difficult because platform APIs cannot (or shouldn't) be invoked from a test case. That is, any part of the plugin code that interacts with the platform API should be wrapped into a class so that it can be mocked and tested by a test framework. But, as you know, the plugin code heavily depends on platform APIs and it is clear that we cannot make everything "testable". My question was about whether you have an "example" test case you have set as your implementation goal but not specifically about the audioplayers_tizen plugin. Being specific on this will help everyone understand what can be tested and what can't be in their plugin code.

**Comment by bbrto21** [comment]
@HakkyuKim 
I think we can make a test bed as tizen-native app for gtest.  this way, we can run our tests on an emulator or device and get the results. tizen-sdk already include gtest as a lib. if you don't mind I'll make a draft when I have free time.

**Comment by swift-kim** [comment]
Closing. Please reopen and assign yourself if anyone is going to work on this issue.
