### ISSUE TITLE
Writting plugins in C#

### ISSUE THREAD

**Issue by ppaneksamsung** [flutter-tizen/plugins#44]
Hello,

As far as I understand, flutter plugins can be developed in other languages than C/C++ and Dart. According to paragraph https://flutter.dev/docs/development/packages-and-plugins/developing-packages#step-1-create-the-package-1, it is possible to develop a flutter plugin in Java and Kotlin for Android and Swift and Objective-C for iOS. Would be possible to develop a flutter plugin in C# for Tizen platform? We would like to access some APIs from Tizen.NET.TV package in a flutter application.

**Comment by xuelian-bai** [comment]
I don't think it's supported now, which API do you want from Tizen.NET.TV?

**Comment by ppaneksamsung** [comment]
Tizen.TV.Multimedia.ESPlayer, Tizen.TV.Security.DrmDecrypt and maybe others. Those APIs are thin wrappers around CAPI so we could theoretically skip the Tizen.NET layer and call CAPI directly from C++, but I'm not sure whether the owners want to reveal the underlying CAPI.

**Comment by xuelian-bai** [comment]
currently we use the method to wrap CAPI into Flutter plugins, it's the better way than wrap upon C#.
we have already wrapped video player which is based on media player, but for ES player, we tried, but since it can only display ES data we didn't implement all.

**Comment by ppaneksamsung** [comment]
Where can I find this 'video player based on media player'? Is it released?

I agree that ESPlayer is a little bit tricky and low level. We consider to implement a Video Player demo application (something like https://github.com/SamsungDForum/JuvoPlayer/tree/master/XamarinPlayer/XamarinPlayer.Tizen.TV) in flutter and looking for a player API.

**Comment by swift-kim** [comment]
As Xuelian already stated, we strongly recommend to write the plugin code in C++ if the C# code you want to interact with in your Dart code is a wrapper of underlying C APIs.

I think you've already spoken personally with Xuelian, but for who are interested with writing plugins in C# rather than C++ or Dart, I'll explain a little bit more in detail. Flutter plugins for Android are written in Java or Kotlin because the platform's native language is Java. (Both Java and Kotlin code transpiles into JVM byte code so basically they are the same thing from the platform's perspective.) The same applies to iOS whose native language is obj-C (or Swift). In the same manner, Tizen plugins are written in C++ because the platform's native language is C++. Although Tizen supports .NET as one of its app types, C# code requires a .NET runtime to be initialized before it can run, so the situation is different from other platforms.

That being said, writing plugins in C# is still possible, at least in theory, because a Flutter app on Tizen TV technically runs on a .NET VM. (This is only because the native app type is not available for use by 3rd-party developers, so flutter-tizen uses the .NET app type as a workaround.) To enable building C# plugins, we first need to create C# binding for Tizen plugins that implements the binary channel interface between the Dart runtime and the .NET runtime. It would be something like the `io.flutter.plugin.common` package for Android plugins. And then C# plugins will be able to register their method call handlers to the engine during app launch (which can be done by the flutter-tizen tool by injecting auto-generated code to the C# app host).

Because it will take quite a bit of effort to implement such things, we plan to challenge only if there's a high demand from the users. Thank you for your comment and if you have further questions or comments, please let us know!

**Comment by ppaneksamsung** [comment]
@swift-kim thanks for the detailed explanation. Before raising this issue, I took a look on the flutter-tizen internals and noticed that the app type is Tizen .NET. I didn't expect that it is possible to develop a flutter plugin in C# now, but as you said, it should be technically possible.

If needed, we will consider to develop a C++ plugin.
