### ISSUE TITLE
Discuss to add tizen_cion plugin.

### ISSUE THREAD

**Issue by upple** [flutter-tizen/plugins#539]
## Background

The Cion is module to communicate and TIDL supports Cion.
Tizen supports Flutter applications.  TIDL supports Dart language for Flutter applications.
The Flutter application can communicate using Cion api. it's generated using TIDL.
We received a request from another department to use cion TIDL in flutter.
So we prepared tizen_cion plugin.(#538)
Please review it.

**Comment by swift-kim** [comment]
Hi. Actually I'm not sure if third-party developers will find this plugin useful, since I can't find any information about Cion on Google except for the official documentation which isn't very informative. If you're mainly targeting internal (VD) developers, you might want to release your code on the CODE GitHub. We already have a number of such plugins in https://github.sec.samsung.net/f-project and https://github.sec.samsung.net/f-project/plugins. This way you don't even need to publish your packages on pub.dev, and instead let users to use [git package dependencies](https://dart.dev/tools/pub/dependencies#git-packages).

Also, I wonder what major advantages this API has over other standard technologies such as TCP/IP and HTTP or other popular technologies that most developers are familiar with.

**Comment by upple** [comment]
Hello.
We discussed your opinion internally.
As you said, it would be better to manage the plugin appfw internally.
If someone has any requirements in the future, it would be nice to discuss them again.
Thank you for your feedback.
