### ISSUE TITLE
[video_player] httpHeaders support

### ISSUE THREAD

**Issue by JMaroz** [flutter-tizen/plugins#621]
Hello,

I'm currently working on a TV app, and we need to set an HTTP header cookie when playing a video. I noticed that the [video_player_tizen](https://github.com/flutter-tizen/plugins/tree/master/packages/video_player#video_player_tizen) does not support this option.

Are you working on this feature? Do you have any ETA?

Thanks,
Andrea

**Comment by swift-kim** [comment]
@xuelian-bai Do you know anything about this? This feature doesn't seem to be supported by any of the TV player APIs as far as I can see.

**Comment by hyue7** [comment]
Hi, @JMaroz  
[video_player_tizen](https://github.com/flutter-tizen/plugins/tree/master/packages/video_player#video_player_tizen) and [video_player_videohole](https://github.com/flutter-tizen/plugins/tree/master/packages/video_player_videohole) not support set http header yet. Since we are now focusing on [avplyer plugin](https://github.com/flutter-tizen/plugins/pull/620), I will try to support it with this plugin. Please follow this, if there is any update on it.

By the way, i find these TV player Apis:
`player_set_streaming_cookie` with mmplayer and `SetStreamingProperty` with plusplayer
But I'm not sure if they're feasible to implement this feature, i will try.
